[package]
name = "arroyo-sdk"
version = "0.15.0-dev"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "SDK for connecting to and interacting with Arroyo stream processing platform"
repository = "https://github.com/ArroyoSystems/arroyo"
documentation = "https://doc.arroyo.dev"
readme = "README.md"

[dependencies]
arroyo-rpc = { path = "../arroyo-rpc" }
arroyo-types = { path = "../arroyo-types" }

tonic = { workspace = true }
prost = { workspace = true }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.12"
tower = { workspace = true }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"

thiserror = "2"
anyhow = "1.0.70"
tracing = "0.1"

reqwest = { version = "0.11", features = ["json"] }
url = "2.4"
async-trait = "0.1"
futures = "0.3"
uuid = { version = "1.3", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# 压缩相关依赖
flate2 = "1.0"
lz4_flex = "0.11"
snap = "1.1"
zstd = "0.13"
lru = "0.14.0"
regex = "1.11.1"
governor = "0.10.0"

[dev-dependencies]
mockito = "1.2.0"
tokio-test = "0.4"
